# Generated by Django 5.0.3 on 2024-03-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='Correo Electronico')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
        ),
    ]
